# Generated by Django 5.0.1 on 2024-02-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id_field', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('char_field', models.CharField(max_length=45)),
                ('number_field', models.BigIntegerField(blank=True, null=True)),
                ('email_field', models.EmailField(max_length=225, unique=True)),
                ('choice_field', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=9)),
                ('text_field', models.TextField()),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_1',
            },
        ),
    ]
